# Generated by Django 6.1.1 on 2026-09-09 04:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_or_name', models.CharField(max_length=100)),
                ('age_years', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(18)])),
                ('age_months', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('default_environment', models.CharField(choices=[('clinic', 'Clinic'), ('home', 'Home'), ('school', 'School'), ('teletherapy', 'Teletherapy')], max_length=20)),
                ('current_presentation', models.TextField(help_text='Free text — grasp stage, endurance, sensory notes, sequencing ability, etc.')),
                ('masking_note', models.TextField(blank=True, help_text="Therapist's own note on whether this child tends to mask distress, if relevant")),
                ('family_cultural_context', models.TextField(blank=True, help_text='Optional — only fill in if genuinely relevant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_domains', to='planner.domain')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_goal_text', models.TextField(help_text='The goal as the therapist first entered it')),
                ('interim_goal_text', models.TextField(blank=True)),
                ('outcome_goal_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='planner.child')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='planner.domain')),
            ],
        ),
        migrations.CreateModel(
            name='GradingLever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('grade_down_description', models.TextField(help_text='How to make it easier')),
                ('grade_up_description', models.TextField(help_text='How to make it harder')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_levers', to='planner.domain')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='children', to='planner.interest'),
        ),
        migrations.CreateModel(
            name='OptionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options_json', models.JSONField(help_text='List of option strings, e.g. ["Isolation first", "Embedded in full routine"]')),
                ('selected_option', models.CharField(blank=True, max_length=300)),
                ('rationale_note', models.TextField(blank=True, help_text="Why this depends on the therapist's/family's judgment, not a default")),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_points', to='planner.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('brief_description', models.TextField()),
                ('presentation_characteristics', models.TextField()),
                ('general_adaptations', models.TextField()),
                ('scope_collaboration_notes', models.TextField(help_text='Which other professionals commonly need to be involved')),
                ('evidence_base_note', models.TextField(blank=True)),
                ('individual_variability_caution', models.TextField(help_text='Mandatory per the schema — never optional, even if brief')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('related_proformas', models.ManyToManyField(blank=True, to='planner.proforma')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='proformas',
            field=models.ManyToManyField(blank=True, help_text='Diagnoses noted for this child, if any', related_name='children', to='planner.proforma'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must be specific and named — never a category (see resource specificity rule)', max_length=200, unique=True)),
                ('resource_type', models.CharField(choices=[('app_digital', 'App/digital'), ('physical_product', 'Physical product'), ('household_item', 'Household item'), ('printable', 'Printable/worksheet'), ('environmental_setup', 'Environmental setup')], max_length=30)),
                ('age_min_months', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max_months', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_type', models.CharField(choices=[('free', 'Free'), ('one_time', 'One-time purchase'), ('subscription', 'Subscription')], max_length=20)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('platform', models.CharField(blank=True, help_text='Digital resources only', max_length=100)),
                ('grading_settings_note', models.TextField(blank=True, help_text='In-product settings that map to grading, for digital resources')),
                ('safety_flags', models.TextField(blank=True)),
                ('sensory_profile', models.TextField(blank=True)),
                ('environment_suitability', models.CharField(blank=True, max_length=200)),
                ('example_functional_play_framings', models.TextField(blank=True)),
                ('cross_discipline_note', models.TextField(blank=True)),
                ('family_cultural_note', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(related_name='resources', to='planner.domain')),
                ('grading_levers', models.ManyToManyField(blank=True, related_name='resources', to='planner.gradinglever')),
                ('interests', models.ManyToManyField(blank=True, related_name='resources', to='planner.interest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_length_minutes', models.PositiveIntegerField(default=45)),
                ('environment', models.CharField(choices=[('clinic', 'Clinic'), ('home', 'Home'), ('school', 'School'), ('teletherapy', 'Teletherapy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_plans', to='planner.goal')),
            ],
        ),
        migrations.CreateModel(
            name='HomeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_plain_language', models.TextField()),
                ('why_this_helps', models.TextField(help_text='1-2 sentences, no clinical terminology')),
                ('activity_description', models.TextField()),
                ('frequency', models.CharField(help_text='e.g. "3-4 times a week, 5 minutes"', max_length=200)),
                ('grade_up_tip_plain', models.TextField(blank=True)),
                ('grade_down_tip_plain', models.TextField(blank=True)),
                ('safety_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_resources', models.ManyToManyField(blank=True, help_text='Should generally be filtered to free/household_item resource_type', related_name='home_programs', to='planner.resource')),
                ('session_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_program', to='planner.sessionplan')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('warm_up', 'Warm-up'), ('main', 'Main'), ('movement_reset', 'Movement reset'), ('warm_down', 'Warm-down')], max_length=20)),
                ('order', models.PositiveIntegerField(help_text='Sequence within the session')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('clinical_reasoning', models.TextField()),
                ('grade_up_note', models.TextField(blank=True)),
                ('grade_down_note', models.TextField(blank=True)),
                ('resources', models.ManyToManyField(blank=True, related_name='activity_blocks', to='planner.resource')),
                ('session_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='planner.sessionplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='planner.domain')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='sub_skills',
            field=models.ManyToManyField(blank=True, related_name='resources', to='planner.subskill'),
        ),
        migrations.CreateModel(
            name='ProformaDomainImplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_it_shows_up', models.TextField()),
                ('design_implication', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.domain')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_implications', to='planner.proforma')),
            ],
            options={
                'unique_together': {('proforma', 'domain')},
            },
        ),
    ]
