# Generated by Django 6.1.1 on 2026-09-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionplan',
            options={'ordering': ['created_at']},
        ),
    ]
